### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jhenrique09**

### CODE REVIEW

**Comment by akhilnarang** [comment]
Any reason for the separate prop for maintainer?

**Comment by akhilnarang** [comment]
Could do something like https://github.com/ResurrectionRemix/android_build/commit/fc423c920387a4e7119b6b6f590968b49a2d6dec I guess

**Comment by jhenrique09** [comment]
Yup, https://github.com/ResurrectionRemix/android_build/commit/fc423c920387a4e7119b6b6f590968b49a2d6dec can be a suitable option.

The main reason for this is: I compile my builds on jenkins, so on updater-script is showing 'jenkins'

**Comment by akhilnarang** [comment]
Yeah can you try the commit I linked, that's the reason for that commit :P

**Comment by jhenrique09** [comment]
Working fine, please consider merging that

**Comment by westcripp** [comment]
lets test this

**Pull request merged**
