### PR TITLE
remove code to fix multirom install issues

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by bdogg718k** [comment]
Looking over it with Akhil..it seems to be the census that this is not necessary. Take a look here. http://gerrit.dirtyunicorns.com/#/c/23896/ Read Alex Cruz's comment.

**Comment by ghost** [comment]
Its easier to remove 1 line of code from a rom to fix numerous devices, that isn't really needed in an aftermarket ROM anyways. Basically that code does an internal system check which is needed for OEM and internal roms. Odviously OEM and internal roms are going to stick to AOSP code and not use multirom.

**Comment by varund7726** [comment]
If this doesnt break Non multi rom stuff Which is users installing only one primary rom then we can merge this

**Comment by ghost** [comment]
Nope, nonmultirom devices aren't affected by this commit.

**Pull request closed without merging**
